export const JOB_TAGS = [
  { id: 29, name: ".NET" },
  { id: 34, name: "Android" },
  { id: 17, name: "Angular" },
  { id: 13, name: "AWS" },
  { id: 14, name: "Azure" },
  { id: 28, name: "C#" },
  { id: 41, name: "CI/CD" },
  { id: 40, name: "DevOps" },
  { id: 23, name: "Django" },
  { id: 11, name: "Docker" },
  { id: 25, name: "FastAPI" },
  { id: 24, name: "Flask" },
  { id: 15, name: "GCP" },
  { id: 26, name: "Go" },
  { id: 44, name: "GraphQL" },
  { id: 4, name: "Hibernate" },
  { id: 36, name: "iOS" },
  { id: 1, name: "Java" },
  { id: 20, name: "JavaScript" },
  { id: 10, name: "Kafka" },
  { id: 35, name: "Kotlin" },
  { id: 12, name: "Kubernetes" },
  { id: 31, name: "Laravel" },
  { id: 42, name: "Microservices" },
  { id: 8, name: "MongoDB" },
  { id: 6, name: "MySQL" },
  { id: 21, name: "NodeJS" },
  { id: 30, name: "PHP" },
  { id: 7, name: "PostgreSQL" },
  { id: 22, name: "Python" },
  { id: 38, name: "QA" },
  { id: 33, name: "Rails" },
  { id: 16, name: "React" },
  { id: 9, name: "Redis" },
  { id: 43, name: "REST" },
  { id: 32, name: "Ruby" },
  { id: 27, name: "Rust" },
  { id: 39, name: "Selenium" },
  { id: 2, name: "Spring" },
  { id: 3, name: "Spring Boot" },
  { id: 5, name: "SQL" },
  { id: 37, name: "Swift" },
  { id: 19, name: "TypeScript" },
  { id: 18, name: "Vue" },
];

export const CATEGORIES = [
  { id: 7, name: "AI/ML" },
  { id: 1, name: "Backend" },
  { id: 19, name: "Blockchain" },
  { id: 15, name: "Business Analyst" },
  { id: 12, name: "Cloud" },
  { id: 6, name: "Data" },
  { id: 13, name: "Database" },
  { id: 11, name: "Design" },
  { id: 5, name: "DevOps" },
  { id: 18, name: "Embedded" },
  { id: 2, name: "Frontend" },
  { id: 3, name: "Fullstack" },
  { id: 17, name: "Game" },
  { id: 4, name: "Mobile" },
  { id: 14, name: "Network" },
  { id: 10, name: "Product" },
  { id: 16, name: "Project Manager" },
  { id: 8, name: "QA" },
  { id: 9, name: "Security" },
  { id: 20, name: "Support" },
];

export const TAG_ID_SET = new Set(JOB_TAGS.map((tag) => tag.id));
export const CATEGORY_ID_SET = new Set(CATEGORIES.map((category) => category.id));
