export const CONSULTING_POSITIONS = [
  "Software Engineer / Lập trình viên",
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "Mobile Developer (iOS/Android)",
  "QA / Tester",
  "DevOps Engineer",
  "Data Analyst",
  "Data Engineer",
  "UI/UX Designer",
  "Product Manager",
  "Project Manager",
  "Business Analyst",
  "Sales Executive",
  "Sales Manager",
  "Marketing Executive",
  "Digital Marketing Specialist",
  "Content Creator",
  "HR Specialist / Recruiter",
  "Customer Support",
  "Accountant / Kế toán",
  "Financial Analyst",
  "Operations Executive",
  "Supply Chain Staff",
  "Warehouse Staff",
  "Administrative Assistant",
  "Graphic Designer",
  "Lecturer / Trainer",
  "Mechanical Engineer",
  "Electrical Engineer",
];

export const CONSULTING_INDUSTRIES = [
  "Công nghệ thông tin (IT/Software)",
  "Thương mại điện tử (E-commerce)",
  "Tài chính / Ngân hàng",
  "Bảo hiểm",
  "Giáo dục / Đào tạo",
  "Y tế / Chăm sóc sức khỏe",
  "Sản xuất / Manufacturing",
  "Logistics / Vận tải",
  "Bán lẻ / Retail",
  "Bất động sản",
  "Xây dựng",
  "Du lịch / Nhà hàng / Khách sạn",
  "Truyền thông / Marketing / Quảng cáo",
  "Nông nghiệp",
  "Năng lượng",
  "Viễn thông",
  "Ô tô / Cơ khí",
  "Thực phẩm & Đồ uống (F&B)",
  "Thời trang",
  "Dịch vụ tư vấn",
  "Game / Giải trí",
  "Phi lợi nhuận (NGO)",
  "Chính phủ / Nhà nước",
  "Startup / Công ty khởi nghiệp",
  "Khác",
];

export const CONSULTING_BUDGET_UNITS = [
  "VND/tháng",
  "VND/năm",
  "USD/tháng",
  "USD/năm",
];
