export const CONSULTING_POSITIONS = [
  // --- IT & Technology Groups ---
  "Senior Java Developer",
  "Senior .NET Developer",
  "Senior Golang Developer",
  "Backend Engineer (Golang)",
  "Senior Java Backend (Banking)",
  "Fullstack Developer",
  "Frontend Engineer (React)",
  "Mobile App Developer (Flutter)",
  "Mobile Developer (iOS/Android)",
  "Embedded Software Engineer",
  "Software Engineer (C#)",
  "E-commerce Developer",
  "QA Automation Lead",
  "QA Engineer",
  "DevOps Engineer",
  "Cloud Solutions Architect",
  "Site Reliability Engineer (SRE)",
  "Cyber Security Specialist",
  "Information Security Officer",
  "Data Scientist",
  "Data Engineer",
  "BI Analyst",
  "AI Researcher",
  "Autonomous Driving AI Engineer",

  // --- Management & Professional Groups ---
  "Product Manager",
  "Product Lead",
  "IT Project Manager",
  "Digital Transformation Lead",
  "Business Analyst (IT)",
  "SAP Consultant / Specialist",
  "Investment Analyst",
  "Financial Analyst",
  "Senior Accountant",
  "Legal Counsel / Compliance",
  "HR Specialist (Tech Recruiting)",

  // --- Design & Creative Groups ---
  "UI/UX Designer",
  "Product Designer",
  "Graphic Designer",
  "Game Logic Programmer",
  "Digital Content Creator",

  // --- Specialized Engineering & Services ---
  "PLC & IoT Systems Engineer",
  "Mechanical Engineer (Chassis)",
  "Electrical Design Engineer",
  "Chemical Engineer",
  "Metallurgical Engineer",
  "Food Technologist",
  "Architect (Project Design)",
  "Civil Engineer",
  "Senior Pilot (A350/B787)",
  "Cabin Crew Lead",
  "Executive Chef",
  "Sales Executive (Real Estate)",
  "Retail Sales Manager",
  "Supply Chain Manager"
];

export const CONSULTING_INDUSTRIES = [
  "Software Development",
  "Data & Analytics",
  "Cloud & DevOps",
  "AI & Machine Learning",
  "Cyber Security",
  "UI/UX Design",
  "Product Management",
  "Project Management",
  "Game Development",
  "IT Support & Networking",
  "Business Analyst",
  "Marketing & Communications",
  "Sales & Business Development",
  "Finance & Accounting",
  "Human Resources",
  "Engineering & Manufacturing",
  "Logistics & Supply Chain",
  "Aviation Services",
  "Construction & Architecture",
  "Legal & Compliance",
  "Agriculture & Food Tech"
];

export const CONSULTING_BUDGET_UNITS = [
  "VND/tháng",
  "VND/năm",
  "USD/tháng",
  "USD/năm",
];
